# Development environment for world_sir
name: sir_env
# Only use conda-forge
channels:
 - conda-forge
dependencies:
 # Environment management tools
 - python
 - pip
 - sortedcollections
 - Shapely
 - pyshp
 # Jupyter & interactive stuff
 #- jupyter=1.0.0
 #- jupyterlab=3.2.9

 # Scientific Python
 - numpy
 - scipy

 # Data tools
 - pandas
 - xarray
 #- netcdf4=1.5.8
 - pytables
 #- ipyleaflet=0.15.0
 #- flake8=4.0.1
 #- dask=2022.2.0
 #- h5py=3.6.0
 #- jinja2=2.11.3
 - matplotlib
 #- scikit-learn=1.0.2

 # Progress Bars and user interaction
 #- tqdm=4.62.3
 #- tqdm=4.62.3
 #- click=8.0.3
 - PyYAML=6.0
 #- ipywidgets=7.6.5

 # Geospatial
 - cartopy=0.20.2
 - geoplot=0.5.0
 - geoviews=1.9.4
 #- geopandas=0.10.2
 # MagGeo Dependencies
 - pip:
    - pygame